### ISSUE TITLE
Update the github workflow surge deployment

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/sef-handbook#24]
**Is your feature request related to a problem? Please describe.**

PR-Preview-Generator workflow needs to be updated since the token is expired.

**Describe the solution you'd like**

Update the [test-pull-requests.yml](https://github.com/sef-global/sef-handbook/blob/main/.github/workflows/test-pull-requests.yml) with the below content

```
name: PR-Preview-Generator
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env:
          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sef-site.surge.sh
          SURGE_TOKEN: aadbfcb04e3dae63bb3561ca05f93eb1
        run: surge ./ $DEPLOY_DOMAIN --token $SURGE_TOKEN
```

**Are you working on it?**
No
